-- VocaLock schema.
--
-- One file, two engines. It runs as-is on PostgreSQL (RDS) and, with the
-- substitutions listed at the bottom, on the SQLite database inside the app.
-- Both sides therefore share column names and semantics, so moving a user's
-- rows up to the server later is a copy rather than a translation.
--
-- Conventions:
--   * money is stored in PAISE as an integer. Never floats for currency.
--   * timestamps are ISO-8601 UTC strings. No local time anywhere.
--   * ids are text so the same value works on device and server.

CREATE TABLE IF NOT EXISTS users (
    id              TEXT        PRIMARY KEY,
    phone           TEXT        NOT NULL UNIQUE,
    created_at      TEXT        NOT NULL,
    last_seen_at    TEXT        NOT NULL,
    app_version     TEXT,
    device_model    TEXT
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id              TEXT        PRIMARY KEY,
    user_id         TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan            TEXT        NOT NULL DEFAULT 'monthly_premium',
    status          TEXT        NOT NULL
                                CHECK (status IN ('trial','active','cancelled','expired','failed')),
    trial_price     INTEGER     NOT NULL,   -- paise
    price           INTEGER     NOT NULL,   -- paise
    currency        TEXT        NOT NULL DEFAULT 'INR',
    provider        TEXT,                   -- 'phonepe' etc; NULL while unpaid
    mandate_id      TEXT,                   -- gateway mandate; NULL until one exists
    started_at      TEXT        NOT NULL,
    valid_until     TEXT        NOT NULL,
    cancelled_at    TEXT
);

-- A user has at most one subscription that is not finished with.
CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_one_live_per_user
    ON subscriptions (user_id)
    WHERE status IN ('trial','active','cancelled');

CREATE INDEX IF NOT EXISTS subscriptions_due
    ON subscriptions (status, valid_until);

-- Append-only ledger. Rows are never updated in place: a correction is a new
-- row, so the history of what was charged always survives.
CREATE TABLE IF NOT EXISTS payments (
    id              TEXT        PRIMARY KEY,
    user_id         TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subscription_id TEXT        REFERENCES subscriptions(id) ON DELETE SET NULL,
    amount          INTEGER     NOT NULL,   -- paise
    currency        TEXT        NOT NULL DEFAULT 'INR',
    type            TEXT        NOT NULL CHECK (type IN ('trial','renewal','refund')),
    status          TEXT        NOT NULL
                                CHECK (status IN ('pending','success','failed','simulated')),
    provider        TEXT,
    provider_txn_id TEXT,
    created_at      TEXT        NOT NULL
);

CREATE INDEX IF NOT EXISTS payments_by_user
    ON payments (user_id, created_at DESC);

-- The same provider transaction must never be recorded twice, however many
-- times a webhook is retried.
CREATE UNIQUE INDEX IF NOT EXISTS payments_provider_txn_unique
    ON payments (provider, provider_txn_id)
    WHERE provider_txn_id IS NOT NULL;

-- One-time codes. Server-side only; the device never stores these.
CREATE TABLE IF NOT EXISTS otp_codes (
    phone           TEXT        PRIMARY KEY,
    code            TEXT        NOT NULL,
    expires_at      TEXT        NOT NULL,
    attempts        INTEGER     NOT NULL DEFAULT 0,
    last_sent_at    TEXT        NOT NULL
);

-- ---------------------------------------------------------------------------
-- PostgreSQL vs SQLite
--
-- This file is written to the intersection of both, so it needs no changes for
-- either. The differences that were deliberately avoided:
--
--   TIMESTAMPTZ   -> TEXT holding ISO-8601 UTC. Comparisons still sort
--                    correctly as strings, which is why the format is fixed.
--   NUMERIC(10,2) -> INTEGER paise. Avoids float money on both engines.
--   SERIAL/UUID   -> TEXT ids generated by the application.
--   ENUM          -> TEXT with a CHECK constraint.
--
-- Partial indexes (the WHERE clauses above) work on PostgreSQL 9.0+ and
-- SQLite 3.8+, so both unique constraints hold on the device too.
-- ---------------------------------------------------------------------------
